### ISSUE TITLE
php7.4.5 complie error

### ISSUE THREAD

**Issue by hsko1220** [OOPS-ORG-PHP/mod_screwim#11]
[이슈]
Ubuntu 18 , php 7.4.5 환경에서 mod_serewim 컴파일 안됨
(PHP 7.4.5 (cli) (built: Apr 19 2020 07:36:30) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.5, Copyright (c), by Zend Technologies )

make install 시도시, 다음과 같은 에러 발생
- mod_screwim/php_screwim.c:198:38 : error : 'zned_stream {aka struct _zend_stream}' has no member named 'mmap'

- mod_screwim/php_screwim.c:227:28 : error : 'ZEND_HANDLE_MAPPED' undeclared (first use in this function); did you mean 'ZEND_HANDLE_FP'?

[상황]
- zlib extention 확인 ( <?php gzopen(); ?> )
- php.ini 설정 완료 ( extention = screwm,so & screwim.enable =1 ) 
- PHP Warning:  PHP Startup: screwim: Unable to initialize module
Module compiled with module API=20170718
PHP    compiled with module API=20190902
These options need to match

**Comment by karenb-ee** [comment]
+1

**Comment by Joungkyun** [comment]
이슈 해결된 1.0.2 release 되었습니다.
