### ISSUE TITLE
Do you also support php8.0?

### ISSUE THREAD

**Issue by wmf34a** [OOPS-ORG-PHP/mod_screwim#13]
Do you also support php8.0?

please...

**Comment by wmf34a** [comment]
php8.0 screwim 되게 해주세요... 제발요 .. 어떻게 설치하나요 ;.... ㅠㅠ

**Comment by leeyunjea** [comment]
ubuntu18.04 에 php8.0 환경에서 지원 가능할까요..??

**Comment by Joungkyun** [comment]
8.0 환경에서 아직 운영을 하지 않아서 ^^;
환경 구성하고 확인해 보겠습니다.

**Comment by Joungkyun** [comment]
3/15 내에 1.0.3 release 예정입니다. 급하시면.. master branch 다운로드 받아서 빌드 하세요.

**Comment by Joungkyun** [comment]
1.0.3 release 되었습니다.
