### ISSUE TITLE
컴파일중 오류가 발생 하였습니다.

### ISSUE THREAD

**Issue by yoonjoongkang** [OOPS-ORG-PHP/mod_screwim#5]
안녕하세요.

make시 add_property_string 매크로에 오류가 발생 하여 문의 드립니다.

[컴파일 환경]
PHP 5.6.31 (cli) (built: Sep 25 2017 14:34:20) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend Guard Loader v3.3, Copyright (c) 1998-2014, by Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Suhosin v0.9.37.1, Copyright (c) 2007-2014, by SektionEins GmbH

[root@localhost:/usr/local/src/mod_screwim-master]# make
/bin/sh /usr/local/src/mod_screwim-master/libtool --mode=compile gcc -m64  -I. -I/usr/local/src/mod_screwim-master -DPHP_ATOM_INC -I/usr/local/src/mod_screwim-master/include -I/usr/local/src/mod_screwim-master/main -I/usr/local/src/mod_screwim-master -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -DHAVE_CONFIG_H  -march=nocona -O2 -pipe   -c /usr/local/src/mod_screwim-master/php_screwim.c -o php_screwim.lo 
mkdir .libs
 gcc -m64 -I. -I/usr/local/src/mod_screwim-master -DPHP_ATOM_INC -I/usr/local/src/mod_screwim-master/include -I/usr/local/src/mod_screwim-master/main -I/usr/local/src/mod_screwim-master -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -DHAVE_CONFIG_H -march=nocona -O2 -pipe -c /usr/local/src/mod_screwim-master/php_screwim.c  -fPIC -DPIC -o .libs/php_screwim.o
/usr/local/src/mod_screwim-master/php_screwim.c:535:55: error: macro "add_property_string" requires 4 arguments, but only 3 given
/usr/local/src/mod_screwim-master/php_screwim.c: In function ‘zif_screwim_seed’:
/usr/local/src/mod_screwim-master/php_screwim.c:535: error: ‘add_property_string’ undeclared (first use in this function)
/usr/local/src/mod_screwim-master/php_screwim.c:535: error: (Each undeclared identifier is reported only once
/usr/local/src/mod_screwim-master/php_screwim.c:535: error: for each function it appears in.)
/usr/local/src/mod_screwim-master/php_screwim.c:536:53: error: macro "add_property_string" requires 4 arguments, but only 3 given
make: *** [php_screwim.lo] 오류 1

즐거운 시간 되세요.

**Comment by Joungkyun** [comment]
PHP5 에서만 발생하는 문제 입니다. PHP 7은 해당 사항 없습니다.
