### ISSUE TITLE
암호화 파일 확장자가 php 인 경우 오류

### ISSUE THREAD

**Issue by kieregh** [OOPS-ORG-PHP/mod_screwim#8]
우선, 좋은 툴을 공개해주셔서 감사드립니다.
설치해서 테스트해보고 있는데요.... 아래의 이슈가 있어서 문의 드립니다.

# 이슈 
암호화된 파일 확장자가 php 인 경우 오류

# 상황
 1) (원본)test.php 파일을 백업(test.backup.php) 한 후 암호화 한다. (test.php.screw 파일 생성)
 2) (암호화된)test.php.screw 파일을 test.php 로 변경할 경우 에러발생 
 3) (암호화된)test.php.screw 파일을 그대로 사용할 경우 기존 (원본)test.php 파일 기능 정상작동
> (암호화된)test.php.screw 파일을 test.abc 로 변경해도 기존 (원본)test.php 파일 기능 정상작동
즉, 확장자가 php 가 아닌 경우는 암호화된 파일이 원본 파일 기능을 정상적으로 수행합니다.

# 배경
본 Tool 을 사용해서 특정(중요) 파일을 암호화해서 타인에게 제공한 경우 만약, 암호화된 파일 확장자가 php 가 아닌 다른 확장자라면 암호화되었다는 지표가 되어 타인의 복호화 의도를 도울 수 있을 것으로 
판단됩니다. 

즉, 암호화된 파일과 일반 파일을 확장자로 구분해줘야 하는 상황이 되어 본 Tool 의 기본의도를 훼손하는 게 아닌가 하는 생각이 듭니다.

이 이슈를 해결할 방법이 없는지 궁금합니다.

감사합니다.

**Comment by Joungkyun** [comment]
질문이 중복되는 것 같은데, mod_screwim 의 사용법 개념을 이해를 못하시는 것 같습니다.

안된다고 하시는 내용과 이전 질문을 봐서는 사용법 개념을 이해를 못한 듯 하여 조금 더 보충 설명을 드립니다.

혹시, 이 개념을 제대로 이해를 하시고 테스트를 하여 에러가 발생한 경우라면, 에러를 재현할 수 있는 코드와 작업 순서등을 알려 주십시오.

일단, --enable-screwim-decrypt 옵션은 사용하지 마십시오. 이 옵션은 cli tool을 사용하기 귀찮을 경우나 자동화 같은 것을 하기 위하여 넣은 기능입니다. 이 함수를 어디다 사용할지에 대한 계획이 없다면 주지 않는 것이 맞습니다.

그리고, 빌드를 한 후에, cli tool로 test.php.screw 로 암호화 파일을 생성 했다면, 빌드된 screwim.so 와 test.php.screw 를 test.php 로 이름을 바꿔서 사용자에게 전달을 해 주면 됩니다.

그리고 전달한 파일을 사용하는 방법은

https://github.com/OOPS-ORG-PHP/mod_screwim/blob/master/README.ko.md 문서의 "***실행***" 섹션을 참고하여 사용자에게 전달해 주면 됩니다.

제가 테스트한 바로는 님이 원하시는 대로 동작을 하고 있어 뭘 어떻게 해 드려야 할지 모르겠습니다. ^^

**Comment by Joungkyun** [comment]
더 이상의 의견이 없어 이슈 종료 합니다.
